name = "krakedkrew-com"
main = "src/_worker.js"
compatibility_date = "2025-08-22"
workers_dev = true

# Serve /public
[assets]
directory = "public"
binding = "ASSETS"

# -----------------------------
# PREVIEW ENV
# -----------------------------
[env.preview]
# Durable Object migrations MUST be an array here
migrations = [
  { tag = "v1", new_sqlite_classes = ["Bus"] }
]
[env.preview.vars]
# CORS allow-list for preview
ALLOWED_ORIGIN = "https://*.workers.dev,https://*.pages.dev"
# command clamp
MAX_TICKETS_PER_CALL = "10000"

# D1 (preview)
[[env.preview.d1_databases]]
binding = "DB"
database_name = "streamdb-preview"
database_id = "71e16e4a-90f3-4b41-88f5-776595f106b8"

# KV (preview)
[[env.preview.kv_namespaces]]
binding = "SESSIONS"
id = "1ae21f8c880b48ea9ad116325023e402"

# DO (preview)
[env.preview.durable_objects]
bindings = [{ name = "BUS", class_name = "Bus" }]

# -----------------------------
# PRODUCTION ENV
# -----------------------------
[env.production]
migrations = [
  { tag = "v1", new_sqlite_classes = ["Bus"] }
]

[env.production.vars]
ALLOWED_ORIGIN = "https://krakedkrew.com"
MAX_TICKETS_PER_CALL = "10000"

# D1 (prod)
[[env.production.d1_databases]]
binding = "DB"
database_name = "streamdb-prod"
database_id = "c02ca30b-63b7-451f-8568-096e90199dfc"

# KV (prod)
[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "813aca9ecfd8458a8dee844e20a3fd2e"

# DO (prod)
[env.production.durable_objects]
bindings = [{ name = "BUS", class_name = "Bus" }]
